use_frameworks!


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

target 'STNetWork_Example' do
  pod 'STNetWork', :path => '../'

  target 'STNetWork_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
